### ISSUE TITLE
NavBar per utente tipo GUEST

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#103]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Modifica NavBar e permessi tenendo conto dell'utente di tipo GUEST.
Inoltre modificare il tempo di redirect delle pagine di errore e del logout

Link task: [https://bugbusters.teamwork.com/tasks/7174385](https://bugbusters.teamwork.com/tasks/7174385)

**Comment by EmanueleC** [comment]
Issue chiusa, viene risolto in issue#100.
