### ISSUE TITLE
Visualizzazione profilo utente

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#104]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Creazione pagina riguardante la visualizzazione del profilo di un utente.

Link task: [https://bugbusters.teamwork.com/tasks/7179410](https://bugbusters.teamwork.com/tasks/7179410)

**Comment by drigoni** [comment]
Fatta nella issue #95
