### ISSUE TITLE
Visualizzazione profilo Super-Admin

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#105]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Creazione pagina riguardante la visualizzazione del profilo di un Super-Admin.

Link task: [https://bugbusters.teamwork.com/tasks/7179430](https://bugbusters.teamwork.com/tasks/7179430)

**Comment by drigoni** [comment]
Fatte nella issue #95
