### ISSUE TITLE
Registrazione di una company come utente non autenticato

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#106]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Creazione pagina riguardante la registrazione di una Company come un utente non autenticato.

Link task: [https://bugbusters.teamwork.com/tasks/7179444](https://bugbusters.teamwork.com/tasks/7179444)

**Comment by drigoni** [comment]
Fatta nella issue #95
