### ISSUE TITLE
Aggiornamento TypeDoc

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#109]
*Codice in cui si trova il problema*:
package.json (da master)

*Descrizione del problema*:
Impostare una versione di typedoc funzionante con la configurazione attuale o aggiornare la configurazione alla nuova versione di typedoc.

Link task: [https://bugbusters.teamwork.com/tasks/7181790](https://bugbusters.teamwork.com/tasks/7181790)

**Comment by korut94** [comment]
Opzioni:
* fissare v.0.3.12
* aggiornare con la configurazione richiesta dalla nuova versione
