### ISSUE TITLE
RouterFacade.ts

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#12]
Activity #2 
Scrivere il modulo RouterFacade.ts.
Vedere la documentazione nella ST per i dettagli

Link task: [https://bugbusters.teamwork.com/tasks/6538171](https://bugbusters.teamwork.com/tasks/6538171)

**Comment by mdipirro** [comment]
Collegata a issue #22 per correzioni di RouterFacade.ts
