### ISSUE TITLE
Aggiungere API per ottenere SuperAdmin

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#130]
*Codice in cui si trova il problema*:
activity #65

*Descrizione del problema*:
Aggiungere l'API per ottenere tutti gli utenti che sono dei SuperAdmin.

Link task: [https://bugbusters.teamwork.com/tasks/7425167](https://bugbusters.teamwork.com/tasks/7425167)

**Comment by Polpetta** [comment]
Me la assegno io perchè ormai l'ho implementata.
