### ISSUE TITLE
Sistemare WebPack

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#38]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Sistemare WebPack o rimuoverlo.

Link task: [https://bugbusters.teamwork.com/tasks/6865551](https://bugbusters.teamwork.com/tasks/6865551)

**Comment by Polpetta** [comment]
Chiudo in quanto è stato messo a posto direttamente nel branch. Al suo posto è stato usato `express.static` come suggerito dai proponenti
