### ISSUE TITLE
DSLModel.ts

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#4]
Activity #2 
Scrivere il modulo DSLModel.ts.
Vedere la documentazione nella ST per i dettagli

Link task: [https://bugbusters.teamwork.com/tasks/6538111](https://bugbusters.teamwork.com/tasks/6538111)

**Comment by korut94** [comment]
@WeissL e @mdipirro è necessario avere il permesso in lettura per modificare e cancellare una DSL?
