### ISSUE TITLE
Correggere punto di accesso

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#46]
*Documento in cui si trova il problema*: 
Manuale Sviluppatore
Activity #45

*Descrizione del problema*:
Correggere punto di accesso (in attesa di risposta da Tullio)

Link task: [https://bugbusters.teamwork.com/tasks/6938667](https://bugbusters.teamwork.com/tasks/6938667)

**Comment by mdipirro** [comment]
collegato a #75, metto @Polpetta come assegnatario

**Comment by Polpetta** [comment]
@mdipirro Che dovrei fare? :sweat_smile:

**Comment by Polpetta** [comment]
Chiudo in quanto ho capito di averla gia' fatta a quanto pare :blush:
