### ISSUE TITLE
Aggiungere esempi di risposta nelle GET

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#48]
*Documento in cui si trova il problema*: 
Manuale Sviluppatore
Activity #65

*Descrizione del problema*:
Aggiungere esempi di risposta nelle GET

Link task: [https://bugbusters.teamwork.com/tasks/6938669](https://bugbusters.teamwork.com/tasks/6938669)

**Comment by mdipirro** [comment]
Seguire quanto scritto nella issue 496 in documentation per APIDoc (processo di codifica)

**Comment by korut94** [comment]
Chiuda perchè invalida. Task assegnato all'issue #84 dell'activity #65.
