### ISSUE TITLE
Migliorare descrizioni API

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#50]
*Documento in cui si trova il problema*: 
Manuale Sviluppatore
Activity #65

*Descrizione del problema*:
Migliorare descrizioni API, rendendole più dettagliate per uno sviluppatore

Link task: [https://bugbusters.teamwork.com/tasks/6938674](https://bugbusters.teamwork.com/tasks/6938674)

**Comment by korut94** [comment]
Chiuso perchè invalida. Inglobato il task in #84 activity #65.
