### ISSUE TITLE
Correggere api/admin/companies

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#54]
Activity #45

api/admin/companies ritorna stato 500 quando si tenta di inserire una nuova company ma i dati non sono corretti

Link task: [https://bugbusters.teamwork.com/tasks/6983298](https://bugbusters.teamwork.com/tasks/6983298)

**Comment by WeissL** [comment]
Cosa passi come dati all'api?
il body della richiesta deve essere : 
{
user : {},
company: {}
}

**Comment by Polpetta** [comment]
Mmm invoco @EmanueleC
Il 04 giu 2016 20:21, "Luca" <notifications@github.com> ha scritto:

**Comment by EmanueleC** [comment]
Sì, infatti faccio così. Vedi issue#60

**Comment by EmanueleC** [comment]
Lo user che gli passo è fatto così:
{
        email : email,
        password : password
}
e la company è fatta così:
{
        name : companyName
}

**Comment by EmanueleC** [comment]
Adesso questo errore non c'è più infatti.

**Comment by WeissL** [comment]
Chiudo come risolta :)
