### ISSUE TITLE
Completare documentazione mancante

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#59]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Completare documentazione mancante nei file che non ci sono.
Manca la documentazione in:
- [x] companyAPI.ts
- [x] sessioneAPI.ts
- [x] main.tsx
- [x] companyActionCreator.ts
- [x] sessionActionCreator.ts
- [x] dispatcher.ts
- [x] cartella components/*

Link task: [https://bugbusters.teamwork.com/tasks/6985562](https://bugbusters.teamwork.com/tasks/6985562)

**Comment by Polpetta** [comment]
Dipendente dalla fine del task #60

**Comment by EmanueleC** [comment]
Nel branch issue#60 sono già documentati companyActionCreator e showCompanies, showCompaniesMembers

**Comment by Polpetta** [comment]
Ok @EmanueleC. Se trovi altre parti gia' documentate non esitare a spuntarle, grazie! :blush:

**Comment by Polpetta** [comment]
@drigoni chiudi se finita :blush:

**Comment by drigoni** [comment]
@Polpetta la chiudo e basta?

**Comment by Polpetta** [comment]
Se e' finita la documentazione si @drigoni
