### ISSUE TITLE
Scrittura pagine riguardanti le companies

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#60]
*Codice in cui si trova il problema*:
activity #37

*Descrizione del problema*:
Sistemare i seguenti punti:
- [ ] Visualizzazione lista companies
- [ ] Visualizzazione membri delle companies
- [ ] Aggiunta di una company
- [ ] Aggiunta di un membro

Link task: [https://bugbusters.teamwork.com/tasks/6986521](https://bugbusters.teamwork.com/tasks/6986521)

**Comment by EmanueleC** [comment]
Devo attendere che il task Revisione API (issue#69) sia completo per proseguire.
