### ISSUE TITLE
Revisione API

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#69]
*Codice in cui si trova il problema*:
activity #65

*Descrizione del problema*:
Revisionare i vari problemi presenti nelle API:
- [ ] Mancanza di documentazione nella ST di alcune API
- [ ] Report degli errori dev'essere conforme a quello della ST
- [ ] Report dei dati dev'essere conforme a quello della ST

Link task: [https://bugbusters.teamwork.com/tasks/7005509](https://bugbusters.teamwork.com/tasks/7005509)

**Comment by mdipirro** [comment]
@Polpetta @WeissL come mai il branch è stato mergiato ma la Issue è ancora aperta? Non eravamo d'accordo che al merce si chiude anche la Issue relativa?

**Comment by Polpetta** [comment]
No, e' un merge temporaneo perche' @WeissL ha deciso che continuera' a lavorare su questo branch e fara' molteplici PR.

**Comment by WeissL** [comment]
Verificate le API di nuovo, quindi questa issue la chiudo

**Comment by Polpetta** [comment]
Se per te è ok va bene @WeissL
Il 12 giu 2016 16:43, "Luca" <notifications@github.com> ha scritto:
