### ISSUE TITLE
Sostituire FIXME con documentazione

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#81]
*Codice in cui si trova il problema*:
activity #65

*Descrizione del problema*:
Sono presenti nella documentazione dei _FIXME_ che indicano documentazione mancante. Risolverli scrivendo la documentazione, in maniera da non consegnare materiale in cui siano presenti dei _FIXME_.

Link task: [https://bugbusters.teamwork.com/tasks/7027470](https://bugbusters.teamwork.com/tasks/7027470)

**Comment by WeissL** [comment]
collegata a issue #50 , @mdipirro quale chiudo delle due?

**Comment by mdipirro** [comment]
Una volta chiusa la pr chiudi entrambe le issue

**Comment by drigoni** [comment]
Sosotiuiti con TODO
