### ISSUE TITLE
Rimuovere campi superflui nel login

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/MaaS#90]
*Codice in cui si trova il problema*:
activity #65

*Descrizione del problema*:
Rimuovere campo "done", "passwordHashed", "passwordIteration", "passwordSalt".

Link task: [https://bugbusters.teamwork.com/tasks/7090875](https://bugbusters.teamwork.com/tasks/7090875)

**Comment by EmanueleC** [comment]
E' stata risolta questa issue? Vedo che è stata mergiata quindi presumo di sì. Chiudo.
